apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "feedback.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "feedback.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- if .Values.environment }}
{{ toYaml .Values.environment | indent 2 }}
{{- end }}
