apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "feedback.fullname" . }}
  labels:
{{ include "feedback.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "feedback.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "feedback.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: {{ include "feedback.fullname" . }}
          env:
            - name: GO_ENV
              value: production
            - name: EMAIL_NOREPLY
              value: feedback@pubg.com
            - name: HTTP_PORT
              value: 80
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/.env
              name: env-secrets
              subPath: .env
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: env-secrets
          secret: 
            defaultMode: 420
            secretName: {{ include "feedback.fullname" . }}-secrets
            resources:
{{ toYaml .Values.resources | indent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
