apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "feedback.fullname" . }}-secrets
spec:
  backendType: vault
  data:
  - key: secret/{{ .Values.deployEnv }}/fider/envFile
    name: .env
  vaultMountPoint: kubernetes
  vaultRole: {{ .Values.deployEnv }}
