apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "feedback.fullname" . }}-secrets
spec:
  backendType: vault
  data:
  - key: secret/{{ .Values.deployEnv }}/fider/env/DATABASE_URL
    name: DATABASE_URL
  - key: secret/{{ .Values.deployEnv }}/fider/env/JWT_SECRET
    name: JWT_SECRET
  - key: secret/{{ .Values.deployEnv }}/fider/env/EMAIL_MAILGUN_API
    name: EMAIL_MAILGUN_API
  - key: secret/{{ .Values.deployEnv }}/fider/env/EMAIL_MAILGUN_DOMAIN
    name: EMAIL_MAILGUN_DOMAIN
  vaultMountPoint: kubernetes
  vaultRole: {{ .Values.deployEnv }}
